title: Buttons
status: ready
context:
  theme: foo
  class: button
  modifier: default
  text: Default Button
variants:
- name: disabled
  status: ready
  context:
    modifier: disabled
    text: Button Disabled
- name: small
  status: ready
  context:
    modifier: small
    text: Button Small
- name: big
  status: ready
  context:
    modifier: big
    text: Button Big
- name: secondary
  status: ready
  context:
    modifier: secondary
    text: Button Secondary
- name: information
  status: ready
  context:
    modifier: information
    text: Button Information
- name: success
  status: ready
  context:
    modifier: success
    text: Button Success
- name: error
  status: ready
  context:
    modifier: error
    text: Button Error
- name: bordered button
  status: ready
  context:
    modifier: bordered
    text: Button Border
- name: bordered button secondary
  status: ready
  context:
    modifier: bordered--secondary
    text: Button Border Secondary
