title: Breadcrumb component
notes: <p>A “breadcrumb” (or “breadcrumb trail”) is a type of secondary navigation scheme that reveals the user’s location in a website or web app.</p> <p>The term comes from the Hansel and Gretel fairy tale in which the two title children drop breadcrumbs to form a trail back to their home.</p> <p>Just like in the tale, breadcrumbs in real-world applications offer users a way to trace the path back to their original landing point.</p>
context:
  theme: foo
  modifier: breadcrumb
variants:
- name: default
  status: ready
  context:
    modifier: default
- name: custom seperater
  status: ready
  context:
    modifier: custom-separator
- name: custom icons
  status: ready
  context:
    modifier: custom-separator-custom-icons
