# title: Link Component
# context:
#     text: This is an example link
#     url: http://www.google.com
title: Links
status: ready
context:
  theme: foo
  text: default link
  url-internal: /page/
  text2: external link
  url-external: http://google.com
  text3: word document
  url-word-document: memo.doc
  text4: pdf document
  url-pdf: /files/1.pdf
  text5: excel document
  url-xls: /files/1.xls
  text6: sound file
  url-sound: /files/1.pcm
  text7: video file
  url-video: /files/1.mov
