title: Card component
status: ready
notes: Cards are containers full of inclusive images and text that serve as entry points to more detailed information.</p> <p>They provide a good balance betqween UI aesthetics and good usability because they are a convenient means of displaying content composed of different elements.
context:
    theme: foo
    modifier: default
    card-media: http://images.grault.com/1920x1280/jpg/image.179.jpg
    card-header: This is an example of the card header
    card-body: This is an example of the card body text. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    card-link: Read More
