title: Icon List
notes: Lists are used to display related data in a list form
status: ready
context:
  theme: foo
  modifier: iconlist--before
  text: This is a default list
variants:
  - name: star
    status: wip
    context:
      modifier: iconlist--star--before
      text: This is a star list
  - name: check
    context:
      modifier: iconlist--check--before
      text: This is an icon list
  - name: Chevron Right
    context:
      modifier: iconlist--chevron-right-circle--before
      text: This is a chevron right list
  - name: Arrow Down
    context:
      modifier: iconlist--arrow-circle-o-down--before
      text: This is a circle down list
  - name: Inbox
    context:
      modifier: iconlist--inbox--before
      text: This is an inbox styled list
  - name: Angle Double Right
    context:
      modifier: iconlist--angle-double-right--before
      text: This is an angle double right styled list
