title: Hero component
status: ready
notes: A hero component is typically a large, full width image on a page that acts as a featured element.
context:
    theme:                  foo
    modifier:               default
    heroMedia:             http:///images.grault.com/1920x1200/jpg/la.jpg
    heroHeader:             Headline
    heroCopy:              Call 123-456-7890 lorem ipsum dolor sit amet, consectetur.
    call-to-action-label:   Call to Action
    call-to-action-link:    http://idealpositions.com
