title: Notification
status: ready
notes: Notifications are used to display feedback.
context:
  theme: foo
  modifier: default
  text: This is the default banner
variants:
  - name: success
    status: prototype
    context:
      modifier: success
      text: This is a success banner
  - name: information
    context:
      modifier: info
      text: This is an info banner
  - name: warning
    context:
      modifier: warning
      text: This is a warning banner
  - name: danger
    context:
      modifier: danger
      text: This is a danger banner
